search_items = [
    "air fryer",
    "almari baju",
    "almari",
    "abaya",
    "aircond",
    "aquarium",
    "applecouture",
    "al quran",
    "air humidifier",
    "baju kurung",
    "baju kurung moden",
    "baju raya 2021",
    "baju meleyu",
    "baju kurung budak",
    "bra",
    "baju meleyu slim fit",
    "blouse women",
    "baju melayu budak",
    "carpet",
    "curtain",
    "casing iphone",
    "cardigan",
    "cardar queen",
    "cadar",
    "cap",
    "cadar single",
    "car accessoriers",
    "dress",
    "dress muslimah",
    "dress women",
    "drone",
    "drawer",
    "diffuser",
    "dumbell",
    "drill",
    "dhia cotton",
    "earphone",
    "evpad",
    "engine oil",
    "eyeshadown",
    "elrah exclusive baju melayu",
    "eyeliner",
    "earphone gaming",
    "earbuds",
    "face mask",
    "face shield",
    "fareha",
    "face mask head loop",
    "fake nails",
    "face mask 3ply",
    "face mask kids",
    "folding bike",
    "fan",
    "garci pro gel kebas",
    "gaming chair",
    "g shock",
    "garci pro gel",
    "gift box",
    "garci pro rawat kebas",
    "garci pro",
    "garci pro kebas saraf",
    "g shock original",
    "iphone",
    "iphone 11",
    "iphone 11 case",
    "iphone case",
    "iphone 12",
    "ipad",
    "iphone x",
    "ikea",
    "iphone 12 pro max casing",
    "jubah muslimah",
    "jam tangan perempuan",
    "jubah",
    "jam tangan lelaki",
    "jamu",
    "jubah leleki",
    "jam tangan",
    "jeans women",
    "jam",
    "kurta",
    "kasut perempuan",
    "kurta leleki",
    "kebaya",
    "kasut leleki",
    "kurung moden",
    "kasult wanita",
    "kurta budak",
    "kasut nike",
    "langsir",
    "long tv box",
    "lampu raya",
    "langsir murah",
    "laptop",
    "lansir sliding door",
    "lego",
    "laptop stand",
    "langsir tingkap",
    "mask",
    "mask headloop",
    "mask 3ply",
    "mainan budak perempuan",
    "mask extender",
    "makeup organizer",
    "meja belajar",
    "mask hitam",
    "mouse pad",
    "neutrovis medical face mask",
    "nike shoe",
    "nintendo switch",
    "notebook",
    "necklace",
    "netflix",
    "nike",
    "nkie air force",
    "neutrovis",
    "office chair",
    "octopus doll",
    "oversize shirt women",
    "oppo a93",
    "office table",
    "one piece",
    "oppo a93 casing",
    "organizer",
    "oppo reno 5",
    "powerbank",
    "poco f3",
    "pop it",
    "priner",
    "purse",
    "pyjamas women",
    "pillow",
    "pencil case",
    "pyjamas",
    "queen bed frame",
    "quran",
    "queen beed sheet",
    "quilt cover",
    "qq 卡",
    "quilt",
    "queen mattress",
    "quran tagging",
    "quby lamp",
    "rak kasut",
    "redmi note 10 pro",
    "rak bukui",
    "ring",
    "rice cooker",
    "rak dapur",
    "rak pinggan",
    "rak baju",
    "rak",
    "sofa",
    "smart watch",
    "sampul duit raya 2021",
    "sling bag",
    "sandal perempuan",
    "shawl",
    "sejadah",
    "sling bag women",
    "skirt",
    "telekung",
    "tudung sarung",
    "tudung bawal",
    "tshirt women",
    "t shirt",
    "tilam"
    "tupperware",
    "tote bag",
    "telekung siti khadijah",
    "ubat kuat",
    "ultraman",
    "ubat kuat jantan",
    "ultraman toy",
    "underwear women",
    "ubat kuat pawang",
    "ubat gemuk",
    "ubat besar zakar",
    "underwear men",
    "vacuum",
    "vivo",
    "vacuum cleaner",
    "vinyl flooring",
    "vitamin c",
    "vans",
    "vivo y20",
    "vitamilk",
    "vaseline",
    "wallpaper",
    "wall paper dinding",
    "wallext woman",
    "watch",
    "water jet",
    "women blouse",
    "wardah",
    "wallet",
    "wardrobe",
    "x70",
    "xs perfect drink",
    "xmax",
    "xs max",
    "x50 car accessories",
    "xdrop",
    "xpander",
    "xes",
    "xiaomi dash cam",
    "yoga mat",
    "young living",
    "y15zr",
    "y15zr accessories",
    "y15",
    "young living essential oil",
    "young living diffuser",
    "y16zr",
    "yoga pants",
    "zanzea",
    "zoe arissa",
    "zanzea blouse",
    "zanzea women s long dress",
    "zip lock plastic bag",
    "zarzou",
    "zanzea dress",
    "zarzou serum",
    "zippo"
    ]